---
title: ""
include-in-header:
  text: |
    <style type="text/css">
      h1, .h1 {
        border-bottom: none;
        padding-bottom: 0.1px;
      }
    </style>
---

::::: {.grid}
:::: {.g-col-12 .g-col-sm-12}
::: {.text-center}

### TEACHING

:::
::::
::::: 

<br>

I have experience teaching for courses in democratic theory, the history of political thought, justice, public policy, and black feminist thought and literature. Copies of my teaching evaluations and sample syllabi are available upon request.

**Govt 402: Justice and the Family** (Instructor, Fall 2025)
<br> Senior seminar examining debates about reproduction, racial justice, gender, and patriarchal domination.

**Gen Ed 1041: From Slavery to #MeToo** (Teaching Fellow, Fall 2021) 
<br> An introductory course on black women’s voices and black feminist thought in the U.S.

**Gov 10: Introduction to Political Theory** (Teaching Fellow, Spring 2022)
<br> An introductory course on the foundations of political theory.

**Gov 1041/DPI 247: Justice by Means of Democracy** (Teaching Fellow, Spring 2023)
<br> A course at the intersection of political theory, theories of justice, and public policy.

<br>

::::: {.grid}
:::: {.g-col-12 .g-col-sm-12}
::: {.text-center}

### Academic Advising

:::
::::
::::: 

<br>

**Concentration Advisor, Government Department** (2021-2024)
<br> Primary academic advisor for Government undergraduate students in Harvard's second largest undergraduate dorm, Quincy House.

**Residential Tutor, Quincy House** (2021-2024)
<br> On-call mentor and advisor to 470 sophomores, juniors, and seniors.

**Senior Thesis Advisor** (2022-2024) 
<br> Advised theses in History and Literature, African and African American Studies, and Government.

<br>
